# Generated by Django 4.1.5 on 2023-03-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_rename_landload_vstatue_landload_landload_vstatus'),
        ('Landload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plotbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotbooking_date', models.DateField(auto_now=True)),
                ('plotbooking_status', models.IntegerField(default=0)),
                ('payment_statues', models.IntegerField(default=0)),
                ('plot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Landload.plot')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userregistration')),
            ],
        ),
    ]
