# Generated by Django 4.1.5 on 2023-03-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landload', '0002_plotbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotbooking',
            old_name='payment_statues',
            new_name='payment_status',
        ),
    ]
