# Generated by Django 4.1.5 on 2023-01-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_workertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workertype',
            old_name='workertype',
            new_name='workertype_name',
        ),
    ]
