# Generated by Django 4.1.5 on 2023-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_adminreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='admin_password',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
