# Generated by Django 4.1.5 on 2023-02-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_details', models.CharField(max_length=50)),
                ('work_image', models.FileField(upload_to='userdocs/')),
                ('work_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
