# Generated by Django 4.1.5 on 2023-03-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_rename_landload_vstatue_landload_landload_vstatus'),
        ('Worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workbooking_date', models.DateField(auto_now=True)),
                ('workbooking_fordate', models.DateField(auto_now=True)),
                ('workbooking_status', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userregistration')),
                ('work_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Worker.work')),
            ],
        ),
    ]
