# Generated by Django 4.1.5 on 2023-03-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_rename_landload_vstatue_landload_landload_vstatus'),
        ('Worker', '0002_workbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='worker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.worker'),
        ),
    ]
