# Generated by Django 4.1.5 on 2023-03-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0003_work_worker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbooking',
            name='workbooking_fordate',
            field=models.DateField(),
        ),
    ]
