# Generated by Django 4.1.5 on 2023-03-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_rename_landload_vstatue_landload_landload_vstatus'),
        ('Worker', '0004_alter_workbooking_workbooking_fordate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_details', models.TextField()),
                ('wbookingdate', models.DateField(auto_now=True)),
                ('wbooking_fordate', models.DateField()),
                ('w_bstatus', models.IntegerField(default=0)),
                ('p_status', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userregistration')),
                ('worker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.worker')),
            ],
        ),
    ]
