# Generated by Django 4.1.5 on 2023-02-10 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_location'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_address', models.TextField(null=True)),
                ('worker_contact', models.CharField(max_length=10)),
                ('worker_email', models.EmailField(max_length=254, unique=True)),
                ('worker_photo', models.FileField(upload_to='userdocs/')),
                ('worker_password', models.CharField(max_length=50, unique=True)),
                ('worker_proof', models.FileField(upload_to='userdocs/')),
                ('worker_vstatue', models.IntegerField(default=0)),
                ('worker_doj', models.DateField(auto_now=True)),
                ('place_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.place')),
                ('worker_typeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.workertype')),
            ],
        ),
    ]
