# Generated by Django 4.1.5 on 2023-02-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_location'),
        ('Guest', '0002_workertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkerType',
            new_name='Worker',
        ),
    ]
