# Generated by Django 4.1.5 on 2023-02-16 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_location'),
        ('Guest', '0003_rename_workertype_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='place_id',
        ),
        migrations.AddField(
            model_name='worker',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.location'),
        ),
    ]
