# Generated by Django 4.1.5 on 2023-02-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_landload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='worker_vstatue',
            new_name='worker_vstatus',
        ),
    ]
