# Generated by Django 4.1.5 on 2023-02-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_rename_worker_vstatue_worker_worker_vstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landload',
            old_name='landload_vstatue',
            new_name='landload_vstatus',
        ),
    ]
