# Generated by Django 4.1.5 on 2023-02-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_rename_landload_vstatue_landload_landload_vstatus'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_content', models.TextField(null=True)),
                ('Complaint_date', models.DateField(auto_now=True)),
                ('Complaint_status', models.IntegerField(default=0)),
                ('Complaint_reply', models.TextField(null=True)),
                ('Complainttype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.complainttype')),
                ('Landload_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.landload')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userregistration')),
                ('worker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.worker')),
            ],
        ),
    ]
